Fixes for newer versions of pandas and numpy (#1278)
* Fix - AttributeError: module 'numpy' has no attribute 'bool'

* update np.object

* Fix update to pandas api

* Fix groupby in dataframes without "stepnumber"

* dummy commit - test push

* Revert "dummy commit - test push"

This reverts commit 13ed15f2f6550dbee3e5f91aba1e4010e6cac773.